server:
  port: 8606

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.166.148:3306/shareclothes
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 1.14.166.148:8848 # nacos服务地址
        ip: 42.193.160.47
        port: 8606
    sentinel:
      transport:
        dashboard: 1.14.166.148:8858
logging:
  level:
    com.yiyi_app.mapper: debug

