server:
  port: 8603

spring:
  application:
    name: business-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.166.148:3306/shareclothes
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848  # nacos服务地址

logging:
  level:
    com.yiyi_app.mapper: debug

feign:
  circuitbreaker:
    enabled: true

alipay:
  appId: 2021000121617741
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCXaGXRN/twpjqpepqNXfbNphmTwvKqb5OJYS/eDckYBSa0kO19/UuIkkuOt4Uye50Y9wF2LSafSmfEyz1gD8GwguSGQl75P/mvQqkmatcPQHRpZIJEmXkCvypdjPs0VpRDrQVwN6PCp+031VY/i4PW1isQ0Qzx3/7vOQUql+f9MEFajz4DV+ClBsAx7BkXAvfgnXKbuoR3fbwwImr1KhUnBEnv2r7qAxsTtcerL4XVtAHeAjtywpfnI4KouLCIL7Kd4Ekg/g+npJJVlMpVl33etO/NW4HlNVtdzcMEoMGYjA8tG2CfFxWBqf9qSz9E42BixmhDABHdTSU0g24I/mknAgMBAAECggEAZcm2oZgMPyhRybx2CNIB6TFggpkOAQzv1+zxfEwyRCa6ZawFLa1KyW7owvKX5l96Nt1gKy2hiHdCGeg0w87z/RGSRrx6EwEyf+PFyeEL4eIIIQ6EEVBILVONTMVJ4F7QYEsCm/Wb73JrpRyUVjYaFSV4YF7aYAWh4vungIINYYWyySsMsSDFahjnx/8heVEJ+BWVjysusRHJFdR23aMoU1HsjVtbiIIDg3phntpoS1q/GcJDU3G3AXrqmsY8G9r8Jsrk8Df9HtFGp5a+s502czd9zS967pzkjccjSwP2Y7eQubkdX91NdoRuNhYbYHJq4juQ/n8/IIsLdnziE9EcGQKBgQDksVKqbFeWT8S+VwOEjS2i+p/qZ5hVmAeWSEJXuPwQd58PPVRyRD/Gv1Bb0UXJxLT0p7IfKMpw3GnA4zva1/u9NxFYz9iVVVsy2zjxJwJwm0NkQNY1dJqzopsXyrlno80L9idKL69O3nTzhjCcA52ZDBiVjafv7zNQ9MUYNu4tSwKBgQCpfKGXSj++E6gbrtBgkVNkZ9Z3DYTog28L/9z63xvZc/uUZwBtu493OtY9tyHB769h+KCxvtnWSzQ3WjAmXXNp8R/bFcyrenyE4tPI5i9tfh4A0mgMZDGzfk6L9Cp5+p1qEA3H1pCe/okZ5B0jqVCLHDBhmN27qCSOF1v5QcjWFQKBgBBIN7R+hjXjdASBOXTkgE1MPrp3qbbeXhvrBR4tw3SAr8hr+2kvRsMlt9jxq2BUKvYIQnxJcTBb4QOkqgxIuFmeZBPIqIjpTNbwGLvCpT/TLhcjLp0bsi/78cLd4hlo5h5l5iI4Buk8mWMFOMzCzSOqYs2zCjPg+exXoPi6YHbFAoGAKB0GRb9d/Me8NukWCnT6zr3AxaaeeUV6R9XD4GBjwACyX3pNYKtOlkKHqE2qoLLwyHhG2Cq6dfyQnDUtRjdB9KYMCxdKvJ8dz3m79EV+niSGR12FIMGp/bh8MKWWVA5bqVmpWU3QJsFJg6Y4u1L8bCA81yyN9jcih7rBmunV9c0CgYBtU1/EZ4WrfWXUsTCLi3oN4P6UbbILfiJSPvH++ha8tHLKm9Gp+lwALf/ZQfmBHNmlxgAirgFcXgdrBT3KQFsR4AgL9Asxc4leoHqOiN8Y9iRVM+nrnhAuaHQW9F6ZTozyI2Q2dwyd+6mgLUrCe7wN/8jLPU4EUx5KTSdFTcrKOw==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkNiivJH6R0RzBHdmeS8SO2l5Z+goQ0sTaFwpep8kiCkgGbs37vUvmoIKtWw+ORDCYyJBonDCSWuDGEhCKk17LIprnKeOWHuoEG7uDo8qCTik0zXvHzkm6EvQpHELVIqeKa3vka1SgYEE7nSN86AlebB0A/jp+4l9U2Z+WJlE0N0Xf4fdCpeDD1nGg1aRNZ84MIXLmSG93s4DQGG9Ty5lXvmJOsODGJMTsEgkJRuU+UoYHydWeaAAF2rbGhlJEDgAbYGY6Xg6VSLmwiSKoBbGLbil/u5bucosFLX/WLluX9Rr2KrQ2iguQt/QkMmn/9D9tAPHhvMHRLmFYTJ2Wnr+OwIDAQAB
  notifyUrl: http://cack7v.natappfree.cc/business/order/notify