server:
  port: 8700

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yiyi_db_v2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123456
  cloud:
    # nacos服务发现
    nacos:
      discovery:
        server-addr: 192.168.1.186:8848  # 写的是我本地的nacos服务地址

logging:
  level:
    com.yiyi_app.mapper: debug